services:
  - type: web
    name: ai-blog-companion
    env: python
    plan: free
    region: singapore
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port $PORT --server.address 0.0.0.0 --server.headless true
    envVars:
      - key: GOOGLE_API_KEY
        sync: false
      - key: HF_TOKEN
        sync: false
